version: '3'
services:
  clientapp_debug:
    container_name: clientcontainer_debug
    restart: always
    stdin_open: true
    build:
      context: ./hammerpoint-fe
      dockerfile: Dockerfile.debug
    volumes:
      - ./hammerpoint-fe:/app
    ports:
      - '3000:3000'
  clientapp_prod:
    container_name: clientcontainer_prod
    restart: always
    build:
      context: ./hammerpoint-fe
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
  serverapp_debug:
    container_name: servercontainer_debug
    restart: always
    build: ./hammerpoint-be
    volumes:
      - ./hammerpoint-be:/usr/src/app
    ports:
      - '3002:3002'
#  serversideprod:
#    container_name: servercontainerprod
#    restart: always
#    build: ./server
#    ports:
#      - '3001:3001'
  mongodbapp:
    container_name: mongodbcontainer
    image: mongo
    ports:
      - '27017:27017'
  database_prod:
    container_name: psqlcontainer
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    env_file:
      - ./hammerpoint-be/.env.prod
    #environment:
     # POSTGRES_USER: user # The PostgreSQL user (useful to connect to the database)
     # POSTGRES_PASSWORD: pass # The PostgreSQL password (useful to connect to the database)
     # POSTGRES_DB: hammerpoint-db # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    command: >
      -c ssl=on 
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key

