version: '3'
services:
  clientapp_debug:
    container_name: clientcontainer_debug
    restart: always
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.debug
    volumes:
      - ./client:/app
    ports:
      - '3000:3000'
  clientapp_prod:
    container_name: clientcontainer_prod
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
  serverapp_debug:
    container_name: servercontainer_debug
    restart: always
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - '3001:3001'
#  serversideprod:
#    container_name: servercontainerprod
#    restart: always
#    build: ./server
#    ports:
#      - '3001:3001'
  mongodbapp:
    container_name: mongodbcontainer
    image: mongo
    ports:
      - '27017:27017'
